### ISSUE TITLE
can't center align images by default due to wordpress + awsm.css limitations

### ISSUE THREAD

**Issue by mccap079** [Rahmon/anatta#1]
The css you're using for this pretty great theme (awsm.css) automatically flushes images to the right when inside `<p>` elements, which is a nice option except that wordpress automatically wraps `<img>` elements in posts inside `<p>` tags thus making the aligned-right style the _only_ way to have images in a post, rather than aligned to center as explained [here](https://igoradamenko.github.io/awsm.css/elements.html#inlines). 

There are currently no feasible workarounds for non-tech savvy users.

I guess the easiest fix would be adding something to the functions.php file to either remove the `<p>` tags from images or add a `<div>` around them instead.

**Comment by Rahmon** [comment]
Hi @mccap079. Thanks for feedback.

The problem occur when the align is set to none.

![screenshot from 2017-11-30 10-55-57](https://user-images.githubusercontent.com/6010232/33431866-1d32c8f2-d5bd-11e7-9959-7e721746306a.png)

I'll fix this. For while a workaround is use the CSS bellow:

`p img.alignnone {
	float: none;
  margin-bottom: 0;
  margin-left: 0;
}`

**Comment by mccap079** [comment]
Oh yeah, just setting the alignment fixes it. Thanks.

**Comment by Rahmon** [comment]
@mccap079 a new version is already available :smile: 

I'll close this issue. Thanks!
